### ISSUE TITLE
Feature report mess using HIDAPI

### ISSUE THREAD

**Issue by zetenynagy** [zetenynagy/dsc_max#1]
Several output reports containing lots of unknown info are coming in when using get_feature_report.

@ginkgobitter I saw your Reddit post, which has helped me make this whole thing, can you help me out with the output reports?

**Comment by ginkgobitter** [comment]
If data is coming in, it is not an output report.
And how does the report buffer you're requesting the feature with look like?
Are you using the controller wired or through bluetooth?

You left no data here, nor are you saying what you're requesting. Without more information I really cannot help you. Not to mention that without access to the console, data that doesn't influence the controller is nothing more than an educated guess on my part.
That said, the [DS4Windows DualSense Suport Ticket](https://github.com/Ryochan7/DS4Windows/issues/1545) has a couple people who have looked into different feature reports. Maybe that can help you?

**Comment by zetenynagy** [comment]
Hey!

I didn't elaborate because I was not sure if you'd actually see the mention. By "data coming in", I meant the data I get every time I request a feature report. However, I'm very new to HID stuff, so I might have mixed some of the terminology up. I'm using the controller wired, and I'm trying to figure out what data should I be sending to the controller to change rumble, LED colors etc. Main goal is to be able to control the adaptive triggers. 

Thanks for that link! I'll definitely look into it, maybe it'll help answer some questions.

I didn't mean to bother you with the unsolicited mention. However, if you have the time and spirit, I could send you these feature reports, and some other minor questions I have. If not, that's obviously fine, I really don't want to take away from your time. 😊 Sorry for bothering again.

**Comment by ginkgobitter** [comment]
I am unsure on how to achieve this on MacOS since I am almost exclusively develop for Windows.
What you want to use the trigger effects is sending a regular output report to the controller. Specifically report type two (the first byte in my array on Reddit.
On Windows there are two options to do that - either HidD_SetOutputReport() or WriteFile() - a brief search turned up that IOHIDDeviceSetReport() and hid_write() might be the equivalent for MacOS. There are slight differences in the way the two methods send reports, but in this case this really doesn't matter and both should work just fine. If I recall correctly, WriteFile() used interrupt-based transfers which not all devices support; however HID devices specifically are required to support them.
Generally, I would assume that you could also just open the virtual device file (/dev/wherever_your_controller_is) and write the report contents to it directly.

Also keep in mind the adaptive trigger effects are still poorly understood. There appear to be a multitude of modes with a bunch of parameters that sometimes defy description. But you should be able to get at least something working based on the things that are known.

**Comment by zetenynagy** [comment]
Thank you! This has pointed me in what seems like the right direction regarding the output reports. 

The support ticket you linked was also very informative about deciphering some of the data.

The adaptive trigger stuff is scary. There are way more skilled people over at DS4Windows, I'll probably borrow the proper implementation if I can't figure it out.

By the way, Max is not a "low-level" programming environment (it's primarily used for multimedia arts), using calls like you mentioned is done automatically by high-level complex abstractions called "objects", which are mostly cross-platform. So thankfully I am spared of having to fiddle with juggling the Windows calls and IOHIDDeviceSetReport() manually, since my goal is to make this work on both major OS-s that support Max, so that people who make interactive art or instruments in Max can have the immersion of the adaptive triggers.

I read in your Reddit post that the DualSense is detected as a 5.1 setup for you. I have tested it using a multichannel mixer in Max and it is detected as four channels, with 3 and 4 being the haptic coils - not 5 + 1 channels (at least on macOS). Sending audio to channels 1 and 2 does not play it from the internal speaker - may I ask how you configured it to utilize the internal speaker as well?

I will now close the issue, and delete it altogether, since this is not really the place for a discussion like this (I resorted to opening an issue because of GitHub's lack of messaging). I'm sorry for contacting you in the first place, if this was an annoyance for you. Thank you for your time and patience, and the detailed answers! Have a great day!
